# Generated by Django 4.1.2 on 2022-11-09 13:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0003_homepage_hero_body_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_us_text',
            field=wagtail.fields.RichTextField(default=''),
        ),
    ]
