# Generated by Django 4.1.2 on 2022-10-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_published_where_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.CharField(blank=True, choices=[('IN', 'International'), ('DO', 'Domestic'), ('PA', 'Patents')], max_length=2),
        ),
    ]
