# Generated by Django 4.1.2 on 2022-10-26 12:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_body_homepage_hero_image_and_more'),
        ('publications', '0004_publication_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationsToHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='home.homepage')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publications.publication')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
