# Generated by Django 4.1.2 on 2022-11-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professorspage_professor_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
