# Generated by Django 4.1.2 on 2022-11-10 06:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_professor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
    ]
