# Generated by Django 4.1.2 on 2022-10-23 16:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0003_homepage_hero_body_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('status', models.CharField(blank=True, choices=[('GR', 'Graduated'), ('ST', 'Studying')], max_length=2)),
                ('rank', models.CharField(blank=True, choices=[('PH', 'Ph.D'), ('MA', 'Master'), ('UN', 'Undergraduate'), ('PR', 'Professor')], max_length=2)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.CreateModel(
            name='MembersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MembersToMembersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('members_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.member')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_list', to='members.memberspage')),
            ],
            options={
                'verbose_name': 'members list',
                'verbose_name_plural': 'members lists',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembersToHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('members_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.member')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_list', to='home.homepage')),
            ],
            options={
                'verbose_name': 'members list',
                'verbose_name_plural': 'members lists',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
