# Generated by Django 4.1.2 on 2022-10-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(blank=True, choices=[('PH', 'Ph.D'), ('MA', 'Master'), ('UN', 'Undergraduate')], max_length=2),
        ),
    ]
